### PR TITLE
serial number of the certificate

### PR DESCRIPTION
**Pull request by chrisDeFouRire**
I needed the serial number of the leaf certificate, I've added it to the output

### CODE REVIEW

**Comment by chrisDeFouRire** [comment]
I ended up adding the fingerprint too... Otherwise it's too difficult (hazardous) to detect changes.
Certstream does send duplicates, which is normal (each log adds new entries over time). The problem is when you have no "primary key" to distinguish between certs.

**Comment by Fitblip** [comment]
Hey @chrisDeFouRire - Thanks for this PR! I'll land and push this so it should go live shortly!



Cheers!
Ryan

**Comment by chrisDeFouRire** [comment]
You know how to keep contributors contributing LOL

**Comment by Fitblip** [comment]
Hah, well as someone who has contributed to quite a few projects myself, I know how I wish more developers would respond!

Cultivating a community isn't the easiest thing in the world, but it's vital that I never forget folks like you are spending their hard-earned free time helping make this project a better thing, and that's why I love doing open source projects. 

In other words, sincerely, thanks! 

giphy

(btw, certstream.calidog.io is updated - you can [check out the new structure here](https://certstream.calidog.io/example.json))

**Pull request merged**
